apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ack-soak-test
  region: us-west-2

managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 80

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ack-soak-controller
      namespace: ack-system
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/PowerUserAccess"
    - "arn:aws:iam::aws:policy/IAMFullAccess"
  - metadata:
      name: ack-core-account
      namespace: ack-system
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AdministratorAccess"