apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: karpenter-provisioner
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: test-infra
  path: ./flux/karpenter-config
  prune: true
  targetNamespace: karpenter
  validation: client
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: karpenter-tags # Installed as part of the CDK